accounts/urls.py
from atexit import register
from unicodedata import name
from django.urls import path

from .views import activate_email, add_address, add_pfp,add_to_cart,cart, decrease_item, del_address, increase_item,login_user,register, remove_cart, remove_coupon,user_logout,profile_view,success
app_name= 'accounts'

urlpatterns = [
    path('login/',login_user,name='login'),
    path('register/',register,name='register'),
    path('logout/',user_logout,name='logout'),
    path('profile/<uid>/',profile_view,name='profile'),
    path('activate/<email_token>/',activate_email,name='activate_profile'),
    path('cart/',cart,name='cart'),
    path('add_to_cart/<uid>/',add_to_cart,name='add_to_cart'),
    path('remove-cart/<cart_item_uid>/',remove_cart,name='remove_cart'),
    path('remove/<uid>/',remove_coupon,name='remove_coupon'),
    path('success/',success,name='success'),
    path('quantity_increase/<uid>',increase_item,name='increase'),
    path('quantity_decrease/<uid>',decrease_item,name='decrease'),
    path('remove_address/<uid>',del_address,name='del'),
    path('add_address/',add_address,name='add_address'),
    path('add_pfp/<uid>',add_pfp,name='pfp'),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('products/',include('product.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from operator import index
from django.urls import path
from .views import index, search
app_name= 'home'

urlpatterns = [
    path('',index,name='home'),
    path('search/',search,name='search')
]

product/urls.py
from django.urls import path
from . views import get_products, home,save_review
# from cart.views import add_to_cart,remove_from_cart
app_name= 'product'

urlpatterns = [
    path('',home,name='home'),
    path('<slug>/',get_products,name='product'),
    path('save-review/<uid>',save_review,name='save_review'),
]

accounts/models.py
from distutils.command.upload import upload
import uuid
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from base.models import BaseModel
from base.email import send_email
from product.models import ColorVariant, Coupon, Item,SizeVariant

class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    is_email_verified = models.BooleanField(default=False)
    email_token = models.CharField(max_length=100,null= True,blank=True)
    profile_img = models.ImageField(upload_to = 'profiles/',default='default.jpg')

    def get_cart_count(self):
        return Cart.objects.filter(cart__is_paid = False,
        cart__user=self.user).count()   


class Address(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='address')
    phone_num = models.CharField(max_length=11,null=True,blank=True)
    first_line = models.CharField(max_length=1000,null=True,blank=True)
    second_line = models.CharField(max_length=1000,null=True,blank=True)
    city = models.CharField(max_length=1000,null=True,blank=True)
    state = models.CharField(max_length=1000,null=True,blank=True)
    pin = models.CharField(max_length=1000,null=True,blank=True)
    
    def __str__(self):
        return "Address"


class Cart(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    is_paid = models.BooleanField(default=False)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL,null=True,blank=True)
    rayzor_pay_order_id = models.CharField(max_length=100,null=True,blank=True)
    rayzor_pay_payment_id = models.CharField(max_length=100,null=True,blank=True)
    rayzor_pay_payment_signature = models.CharField(max_length=100,null=True,blank=True)

    def get_cart_total(self):
        cart_items = self.cart_items.all()
        price =[]
        gst_price = []
        for cart_item in cart_items:
            a,b =cart_item.get_product_price()
            price.append(b)
            gst_price.append(a)

        if self.coupon:
            if self.coupon.min_amount<sum(price):
                return [sum(price)- self.coupon.discount_price,sum(gst_price)- self.coupon.discount_price] 
        return [sum(price),sum(gst_price)]

    def get_items(self):
        cart_items = self.cart_items.all()
        return cart_items

    def get_user(self):
        return self.user


class CartItems(BaseModel):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='cart_items')
    product = models.ForeignKey(Item,on_delete=models.SET_NULL,null=True,blank=True,related_name='product')
    color_variant = models.ForeignKey(ColorVariant,on_delete=models.SET_NULL,null=True,blank=True)
    size_variant = models.ForeignKey(SizeVariant,on_delete=models.SET_NULL,null=True,blank=True)
    quantity = models.IntegerField(default=1)

    def get_product_price(self):
        price = [self.product.price*self.quantity]

        if self.color_variant:
            color_v_price = self.color_variant.price
            price.append(color_v_price)
        if self.size_variant:
            size_v_price = self.size_variant.price
            price.append(size_v_price)
        return [sum(price)*0.18+sum(price),sum(price)]
    
    def get_gst_price(self):
        return self.product.price*0.18

    def items(self):
        return self.cart.get_total_price()


@receiver(post_save,sender=User)
def send_email_token(sender,instance,created,**kwargs):
    try:
        if created:
            email_token=str(uuid.uuid4())
            Profile.objects.create(user=instance,email_token=email_token)
            email=instance.email
            send_email(email,email_token)
    except Exception as e:
        print(e)

accounts/views.py
from typing import ItemsView
from django.conf import settings
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from requests import request
from accounts.models import Address, Cart, CartItems
from base.email import send_invoice
from base.helper import save_pdf
from product.models import ColorVariant, Item, SizeVariant,Coupon
from django.http import HttpResponseRedirect
import razorpay
from accounts.models import Profile
# Create your views here.

def login_user(request):

    if request.method=='POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username=email)
        if not user_obj.exists():
            messages.warning(request, 'Email is already taken')
            return HttpResponseRedirect(request.path_info)

        if not user_obj[0].profile.is_email_verified:
            messages.warning(request,'Your account is not verified')
            return HttpResponseRedirect(request.path_info)

        user_obj = authenticate(username=email,password=password)
        if user_obj:
            login(request,user_obj)
            return redirect('/')

        messages.warning(request,'An email has been sent to your mail')
        return HttpResponseRedirect(request.path_info)
        
    return render(request,'accounts/login-register.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('/')


def register(request):

    if request.method=='POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email_id')
        password = request.POST.get('password')
        print(first_name,last_name,email,password)

        user_obj = User.objects.filter(username=email)
        if user_obj.exists():
            messages.warning(request, 'Email is already taken')
            return HttpResponseRedirect(request.path_info)
        user_obj = User.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=email
        )
        user_obj.set_password(password)
        user_obj.save()
        messages.warning(request,'An email has been sent to your mail')
        return HttpResponseRedirect(request.path_info)

    return render(request,'accounts/login-register.html')


def activate_email(request,email_token):
    try:
        user = Profile.objects.get(email_token=email_token)
        user.is_email_verified = True
        user.save()
        return redirect('/')
    except Exception as e:
        return HttpResponse('Invalid Email token')

@login_required
def cart(request):
    cart_obj=None
    try:
        cart_obj = Cart.objects.filter(is_paid = False,user=request.user)[0]
    except Exception as e:
        print(e)
    if request.method=='POST':
        
        coupon = request.POST.get('coupon')
        coupon_obj = Coupon.objects.filter(coupon_code__icontains = coupon)
        if not coupon_obj.exists():
            messages.warning(request,'Invalid Coupon')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        if cart_obj.coupon:
            messages.warning(request,'Coupon Already Applied')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        if cart_obj.get_cart_total()[0]<=coupon_obj[0].min_amount:
            messages.warning(request,f'Amount should be greater than {coupon_obj[0].min_amount}')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        if coupon_obj[0].is_expired:
            messages.warning(request,'Coupon expired')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        cart_obj.coupon = coupon_obj[0]
        cart_obj.save()
        messages.success(request,'Coupon Applied')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    if cart_obj:
        items = cart_obj.get_items()
        price,price_gst = cart_obj.get_cart_total()
        gst = price*0.18
        if price:
            client = razorpay.Client(auth=(settings.KEY, settings.SECRET))
            payment = client.order.create({'amount' : price*100, 'currency' : 'INR','payment_capture' : 1})
            cart_obj.rayzor_pay_order_id = payment['id']
            cart_obj.save()
            print(cart_obj.rayzor_pay_order_id)
            context = {'cart':cart_obj,'cart_items':items,'price':price,'payment':payment,'price_gst':price_gst,'gst':gst}
        else:
            context = {'cart':None ,'price':0,'cart_items':None,'payment':None,'price_gst':0}
    else:
        context = {'cart':None ,'price':0,'cart_items':None,'payment':None,'price_gst':0}
    return render(request,'accounts/cart.html',context)

@login_required
def add_to_cart(request,uid):
    variant = request.GET.get('variant')
    product = Item.objects.get(uid=uid)
    user = request.user
    cart,_ = Cart.objects.get_or_create(user=user,is_paid=False)
    cart_item = CartItems.objects.create(cart=cart,product=product)
    if variant:
        variant = request.GET.get('variant')
        size_variant = SizeVariant.objects.get(size = variant)
        cart_item.size_variant = size_variant
        cart_item.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def remove_cart(request,cart_item_uid):
    try:
        cart_item = CartItems.objects.get(uid = cart_item_uid)
        cart_item.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    except Exception as e:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def remove_coupon(request,uid):
    cart = Cart.objects.get(uid=uid)
    cart.coupon = None
    cart.save()
    messages.success(request,'Coupon Removed')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def profile_view(request,uid):
    user = Profile.objects.get(uid=uid)
    context = {'user':user}
    prev_orders = None
    try:
        prev_orders =Cart.objects.filter(user=user.user,is_paid=True)
    except Exception as e:
        print(e)
    
    if prev_orders:
        items=CartItems.objects.none()
        for cart in prev_orders:
            items|=cart.get_items()
        context['items']=items
    return render(request,'accounts/profile.html',context)


def add_address(request):
    if request.method=='POST':
        ph = request.POST.get('phone')
        first_line = request.POST.get('first_line')
        second_line = request.POST.get('second_line')
        city = request.POST.get('city')
        state = request.POST.get('state')
        pin = request.POST.get('pin')
        user = request.user
        address = Address.objects.create(
            user = user,
            phone_num = ph,
            first_line=first_line,
            second_line=second_line,
            city = city,
            state = state,
            pin = pin,
        )
        address.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request,'accounts/address.html')


def del_address(request,uid):
    address = Address.objects.get(uid=uid)
    address.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


from num2words import num2words
def success(request):
    order_id = request.GET.get('order_id')
    print(order_id)
    cart=None
    try:
        cart = Cart.objects.get(rayzor_pay_order_id=order_id)
        user = cart.get_user()
        email = user.username
        cart.is_paid = True
        cart.save()

        item = cart.get_items()
        total = cart.get_cart_total()[1]
        price_in_words = str(num2words(total))
        price_in_words.replace('-',' ')
        price_in_words.capitalize()

        coupon = cart.coupon

        invoice_content = {'user':user,'payment_id':order_id,'order':item ,'total':total, "price_in_word":price_in_words,'coupon':coupon}
        send_mail,_ = save_pdf(invoice_content)
        send_invoice(email,send_mail)

        return render(request,'success.html')
    except Exception as e:
        # messages.warning(request,'Server error! Try again!')
        print(e)
        return render(request,'error.html')


def increase_item(request,uid):
    cart_item = CartItems.objects.get(uid=uid)
    cart_item.quantity = cart_item.quantity + 1
    cart_item.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def decrease_item(request,uid):
    cart_item = CartItems.objects.get(uid=uid)
    cart_item.quantity = cart_item.quantity - 1
    if(cart_item.quantity==0):
        cart_item.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        cart_item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def add_pfp(request,uid):
    if request.method=='POST':
        img = request.FILES.get('img')
        user = Profile.objects.get(uid=uid)
        user.profile_img=img
        user.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/accounts/cart.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% load static %}
{% block start %}
<link rel="stylesheet" href="{% static "accounts/cart.css" %}">
<section class="Cart">
    {% if user.is_authenticated %}
    <div class="CartContainer">
        <div class="Header">
            <h3 class="Heading">Shopping Cart</h3>
            <h5 class="Action">Remove all</h5>
        </div>
        {% if cart_items %}
            {% for item in cart_items %}
            <div class="Cart-Items">
                <div class="image-box">
                    <img src="{{ item.product.product_images.all.0.image.url }}" style="height:120px" />
                </div>
                <div class="abt">
                    <h1 class="title"><a href='{%url 'product:product' item.product.slug %}'>{{ item.product.title }}</a>
                    </h1>
                    <div class="subtitle">{{ item.product.preview_text }}</div>
                    <h3 class="subtitle">{{ item.size_variant }} {{ item.color_variant }}</h3>
                </div>
                <div class="counter">
                    <div class="btn"><a href="{% url "accounts:increase" item.uid %}">+</a></div>
                    <div class="count">{{ item.quantity }}</div>
                    <div class="btn"><a href="{% url "accounts:decrease" item.uid %}">-</a></div>
                </div>
                <div class="prices">
                    <div class="amount">${{ item.product.price }}</div>
                    <div class="save"><u>Save for later</u></div>
                    <div class="remove"><u><a href="{% url "accounts:remove_cart" item.uid %}">Remove</a> </u></div>
                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="cart-items" style="height:150px ;">
                <h1 style="padding-top:5% ; font-family:'Inter'">Shopping cart is Empty!</h1>
            </div>
        {% endif %}
    </div>
    </div>
    <div class="costs">
        <form method="POST">
            {% csrf_token %}
            {% include "alert.html" %}
            <input type="text" name="coupon" placeholder="CouponCode" class="text">
            <button type="submit" class="button">Apply coupon</button>
        </form>
        {% if cart.coupon %}
        <div>
            <a href="{% url "accounts:remove_coupon" cart.uid %}"><button class="button">{{ cart.coupon.coupon_code }}</button></a>
        </div>
        {% endif %}
        <div class="bill">
            <h1>Total</h1>
            <p>Total Price : &emsp; {{ price }}</p>
            {% if price_gst %}
            <p>Gst Invoice:&emsp; {{ gst }}</p>
            <p>Total Price :&emsp; {{ price_gst }}</p>
            {% endif %}
        </div>
        {% if user.address.all %}
        <button class="button" id="rzp-button1">Checkout</button></a>
        {% else %}
        <button data-modal-target="#modal" style="margin:5% 2% ; background-color: #03395B; color: white; border-radius: 5px; border: transparent; padding: 10px 30px; cursor: pointer;">Add Address</button>
        <div class="modal" id="modal">
            <div class="modal-header">
                <div class="title">Add Address</div>
                <button data-close-button class="close-button">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url "accounts:add_address" %}">
                    {% csrf_token %}
                    <div>
                        <span><p class="text-al">Phone Number</p></span>
                        <input type="text" required name="phone" class="text" placeholder="First line of address" />
                    </div>
                    <div>
                        <span><p class="text-al">First line</p></span>
                        <input type="text" required name="first_line" class="text" placeholder="First line of address" />
                    </div>
                    <div>
                        <span><p class="text-al">Second Line</p></span>
                        <input type="text" required name="second_line" class="text" placeholder="Second Line of Address" />
                    </div>
                    <div>
                        <span><p class="text-al">City</p></span>
                        <input type="text" required name="city" class="text" placeholder="City" />
                    </div>
                    <div>
                        <span><p class="text-al">State</p></span>
                        <input type="text" required name="state" class="text" placeholder="State" />
                    </div>
                    <div>
                        <p class="text-al">Pin Code</p>
                        <input type="text" required name="pin" class="text" placeholder="Pincode" />
                    </div>

                    <button type="submit" class="button">Add</button>
                </form>
            </div> 
        </div>
        <div id="overlay"></div>
        {% endif %}
    </div>
    {% else %}
    <div class="CartContainer">
        <h1>
            Kindly Login!
            have not account? Register!
        </h1>
    </div>
    {% endif %}
</section>
<script src="{% static "accounts/cart.js" %}"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js" ></script>
<script>
    var options = {
        "key": "rzp_test_JNrVuhqE6brQ0r",
        "amount": "{{ payment.amount }}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "INR",
        "name": "Shopall Ecommerce",
        "description": "Purchases",
        "image": "https://example.com/your_logo",
        "order_id": "{{ payment.id }}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
        "handler": function (response){

            window.location.href = `http://127.0.0.1:8000/accounts/success/?order_id={{ payment.id }}`
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response){
            alert(response.error.code);
            alert(response.error.description);
            alert(response.error.source);
            alert(response.error.step);
            alert(response.error.reason);
            alert(response.error.metadata.order_id);
            alert(response.error.metadata.payment_id);
    });
    document.getElementById('rzp-button1').onclick = function(e){
        rzp1.open();
        e.preventDefault();
    }

</script>

{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{user.user.first_name}}-Profile{% endblock %}
{% block start %}
<link rel="stylesheet" href="{% static "accounts/profile.css" %}">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;400;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<section class="account">
    <div class="pfp">
        <div class="circle"><img src="/media/{{ user.profile_img }}" alt="pfp"></div>
        <h1>{{user.user.first_name}} {{ user.user.last_name }}</h1>
        <h3 onclick="document.getElementById('content').innerHTML=document.getElementById('info').innerHTML;" style="cursor: pointer;">profile</h3>
        <h3 onclick="document.getElementById('content').innerHTML=document.getElementById('cart').innerHTML;" style="cursor: pointer;">Orders</h3>
        <h3 onclick="document.getElementById('content').innerHTML=document.getElementById('password-change').innerHTML;">Change Password</h3>
        <h3><a href="{% url "accounts:add_address" %}" style="cursor: pointer;color: red;"> Add Address</a></h3>
        <h3><a href="{% url "accounts:logout" %}" style="color: red;">LogOut</a></h3>
    </div>
    <div id="content" class="info">
        <button data-modal-target="#modal" style="margin:5% 2% ; background-color: #03395B; color: white; border-radius: 5px; border: transparent; padding: 10px 30px; cursor: pointer;">Add/update profile picture</button>
        <div class="modal" id="modal">
            <div class="modal-header">
                <div class="title">Add Profile Picture</div>
                <button data-close-button class="close-button">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url "accounts:pfp" user.uid %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="img" style="margin-right:2% ;">Add Photo</label><input type="file" name="img" id="img">
                    <button type="submit" style="margin-left:2% ; background-color: #03395B; color: white; border-radius: 5px;
                    border: transparent; padding: 10px 30px; cursor: pointer;">Add</button>
                </form>
            </div>
        </div>
        <div id="overlay"></div>
        <div class="email-address">
            <div class="email">
                <h3>Email</h3>
                <p>{{user.user.email}}</p>
            </div>
            <div class="Phone">
                <h3>Phone</h3>
                <p>{{user.user.address.all.0.phone_num}}</p>
            </div>
            <div class="address">
                {% if user.user.address.all %}
                {% for address in user.user.address.all %}
                <h3>Address: &emsp; <a href="{% url "accounts:del" address.uid %}">&times;</a></h3>
                <p>
                    {{ address.first_line }}<br>
                    {{ address.second_line }}<br>
                    {{address.city}},{{ address.state }}<br>
                    {{ address.pin }},India <br><br>
                </p>
                {% endfor %}
                {% else %}
                <h1 style="margin:5%;"><a href="{% url "accounts:add_address" %}" style="cursor: pointer;color: red;">Add an address</a></h1>
                {% endif %}
            </div>
        </div>
        <div class="social-links">
            <p>Share At: </p>
            <a href="#">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="#">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
                <i class="fab fa-whatsapp"></i>
            </a>
            <a href="#">
                <i class="fab fa-pinterest"></i>
            </a>
        </div>
    </div>
    
</section>
<div class="info" id="info" style="display: none;">
    <button data-modal-target="#modal" style="margin:5% 2% ; background-color: #03395B; color: white; border-radius: 5px; border: transparent; padding: 10px 30px; cursor: pointer;">Add/update profile picture</button>
        <div class="modal" id="modal">
            <div class="modal-header">
                <div class="title">Add Profile Picture</div>
                <button data-close-button class="close-button">&times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url "accounts:pfp" user.uid %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label for="img" style="margin-right:2% ;">Add Photo</label><input type="file" name="img" id="img">
                    <button type="submit" style="margin-left:2% ; background-color: #03395B; color: white; border-radius: 5px;
                    border: transparent; padding: 10px 30px; cursor: pointer;">Add</button>
                </form>
            </div>
        </div>
        <div id="overlay"></div>
    <div class="email-address">
        <div class="email">
            <h3>Email</h3>
            <p>{{user.user.email}}</p>
        </div>
        <div class="Phone">
            <h3>Phone</h3>
            <p>{{user.user.address.all.0.phone_num}}</p>
        </div>
        <div class="address">
            {% for address in user.user.address.all %}
            <h3>Address: &emsp; <a href="{% url "accounts:del" address.uid %}">&times;</a></h3>
            <p>
                {{ address.first_line }}<br>
                {{ address.second_line }}<br>
                {{address.city}},{{ address.state }}<br>
                {{ address.pin }},India <br><br>
            </p>
            {% endfor %}
        </div>
    </div>
    <div class="social-links">
        <p>Share At: </p>
        <a href="#">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#">
            <i class="fab fa-twitter"></i>
        </a>
        <a href="#">
            <i class="fab fa-instagram"></i>
        </a>
        <a href="#">
            <i class="fab fa-whatsapp"></i>
        </a>
        <a href="#">
            <i class="fab fa-pinterest"></i>
        </a>
    </div>
</div>
<section id="cart" style="display: none;">
    <h1>Previous Purchase</h1>
    {% if items %}
        {% for item in items %}
            <div class="Cart-Items">
                <div class="image-box">
                    <img src="{{ item.product.product_images.all.0.image.url }}" style="height:120px" />
                </div>
                <div class="abt">
                    <h1 class="title"><a href="{%url "product:product" item.product.slug %}">{{ item.product.title }}</a>
                    </h1>
                    <div class="subtitle">{{ item.product.preview_text }}</div>
                    <h3 class="subtitle">{{ item.size_variant }} {{ item.color_variant }}</h3>
                </div>
                <div class="counter">
                    <div class="count">{{ item.quantity }}</div>
                </div>
                <div class="prices">
                    <div class="amount">${{ item.product.price }}</div>
                </div>
            </div>
        {% endfor %}
    {% else %}
    <h2>No Items purchased!</h2>
    {% endif %}
</section>
<script>
    const openModalButtons = document.querySelectorAll('[data-modal-target]')
    const closeModalButtons = document.querySelectorAll('[data-close-button]')
    const overlay = document.getElementById('overlay')

    openModalButtons.forEach(button => {
        button.addEventListener('click', () => {
            const modal = document.querySelector(button.dataset.modalTarget)
            openModal(modal)
        })
    })

    overlay.addEventListener('click', () => {
        const modals = document.querySelectorAll('.modal.active')
        modals.forEach(modal => {
            closeModal(modal)
        })
    })

    closeModalButtons.forEach(button => {
        button.addEventListener('click', () => {
            const modal = button.closest('.modal')
            closeModal(modal)
        })
    })

    function openModal(modal) {
        if (modal == null) return
        modal.classList.add('active')
        overlay.classList.add('active')
    }

    function closeModal(modal) {
        if (modal == null) return
        modal.classList.remove('active')
        overlay.classList.remove('active')
    }
</script>
{% endblock %}