accounts/urls.py
from atexit import register
from unicodedata import name
from django.urls import path

from .views import activate_email, add_address, add_pfp,add_to_cart,cart, decrease_item, del_address, increase_item,login_user,register, remove_cart, remove_coupon,user_logout,profile_view,success
app_name= 'accounts'

urlpatterns = [
    path('login/',login_user,name='login'),
    path('register/',register,name='register'),
    path('logout/',user_logout,name='logout'),
    path('profile/<uid>/',profile_view,name='profile'),
    path('activate/<email_token>/',activate_email,name='activate_profile'),
    path('cart/',cart,name='cart'),
    path('add_to_cart/<uid>/',add_to_cart,name='add_to_cart'),
    path('remove-cart/<cart_item_uid>/',remove_cart,name='remove_cart'),
    path('remove/<uid>/',remove_coupon,name='remove_coupon'),
    path('success/',success,name='success'),
    path('quantity_increase/<uid>',increase_item,name='increase'),
    path('quantity_decrease/<uid>',decrease_item,name='decrease'),
    path('remove_address/<uid>',del_address,name='del'),
    path('add_address/',add_address,name='add_address'),
    path('add_pfp/<uid>',add_pfp,name='pfp'),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls')),
    path('products/',include('product.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from operator import index
from django.urls import path
from .views import index, search
app_name= 'home'

urlpatterns = [
    path('',index,name='home'),
    path('search/',search,name='search')
]

product/urls.py
from django.urls import path
from . views import get_products, home,save_review
# from cart.views import add_to_cart,remove_from_cart
app_name= 'product'

urlpatterns = [
    path('',home,name='home'),
    path('<slug>/',get_products,name='product'),
    path('save-review/<uid>',save_review,name='save_review'),
]

base/models.py
from django.db import models
import uuid

class BaseModel(models.Model):
    uid = models.UUIDField(primary_key=True , editable=False, default=uuid.uuid4)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

templates/alert.html
{% if messages %}
    {% for m in messages %}
    <div class="alert alert-{% if m.tags %} class="{{ m.tags }}" {% endif %}" role="alert">
        {{ m }}
    </div>
    {% endfor %}
{% endif %}

<style>
    .warning{
        color: red;
        background-color: rgb(243, 150, 150);
        font-family: 'Inter';
        font-size: medium;
    }
    .success{
        color: green;
        background-color: rgb(178, 248, 178);
        font-family: 'Inter';
        font-size: medium;
    }
</style>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "home/style.css" %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;400;800&display=swap" rel="stylesheet">
    <script src="{% static "product/style.js" %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body> 
    <section id="navbar">
        <div class="navbar-items">
            <div class="pages">
                <a href="#" class="text-small"><img src="#" alt="logo"></a> 
            </div>
            <div class="pages scrollto active">
                <a href="{% url "home:home" %}" class="text-small">Home</a> 
            </div>
            <div class="pages scrollto">
                <a href="{% url "product:home" %}" class="text-small">Categories</a> 
            </div>
            <div class="pages scrollto">
                <a href="#about" class="text-small">About Us</a> 
            </div>
            <div class="pages scrollto">
                <a href="#contact" class="text-small">Contact</a> 
            </div>
        </div>
        <div class="search-bar">
            <form method="POST" action="{% url "home:search" %}">
                {% csrf_token %}
                <input type="text" name="text" placeholder="search">
            </form>
        </div>
        <div class="login-cart">
            <div class="pages">
                <a href="{% url "accounts:cart" %}" class="text-small">Cart</a> 
            </div>
			{% if user.is_authenticated %}
			<div class="pages">
                <a href='{% url 'accounts:profile' user.profile.uid %}' class="text-small">Profile</a> 
            </div>
            <div class="pages">
                <a href="{% url "accounts:logout" %}" class="text-small">Logout</a> 
            </div>
			{% else %}
            <div class="pages">
                <a href="{% url "accounts:login" %}" class="text-small">Login</a> 
            </div>
            <div class="pages">
                <a href="{% url "accounts:register" %}" class="text-small">Register</a> 
            </div>
			{% endif %}
        </div>
    </section>

	{% block start %}

	{% endblock %}

    <section class="footer" id="contact">
        <div class="contact">
            <div class="map">
                    <iframe style="border:0; width: 100%; height: 300px; padding-top: 15%;"
                      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3650.1210188251025!2d86.43899201493427!3d23.814295284557907!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39f6bc9fac678481%3A0x122cb1d133a89995!2sIndian%20Institute%20of%20Technology%20(Indian%20School%20of%20Mines)%2C%20Dhanbad!5e0!3m2!1sen!2sin!4v1650273164700!5m2!1sen!2sin"
                      width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                      referrerpolicy="no-referrer-when-downgrade" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
        <div class="links text-small">
            <img src="#" alt="logo">
            <h3>Shopall</h3>
            <p>
              place<br>
              city,145236<br>
              India <br><br>
              <strong>Phone:</strong> +91 7943216655<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
        </div>
        <div class="links">
            <a href="#" class=" text-small">Home</a>
            <a href="#" class=" text-small">Categories</a>
            <a href="#" class=" text-small">Products</a>
        </div>
        <div class="links text-large">
            <a href="#" class=" text-small">About</a>
            <a href="#" class=" text-small">Customer Service</a>
            <a href="#" class=" text-small">Enquiry</a>
        </div>
    </section>

    <section class="socials">
        <a href="#"><img src="{% static "images/353424_instagram_logo_icon.png" %}" alt="instagram"></a>
        <a href="#"><img src="{% static "images/350974_facebook_logo_icon.png" %}" alt="facebook"></a>
        <a href="#"><img src="{% static "images/353427_logo_twitter_icon.png" %}" alt="twitter"></a>
        <a href="#"><img src="{% static "images/5279116_pin_pinterest_inspiration_pinterest logo_icon.png" %}" alt="pinterest"></a>
    </section>
    <section class="footer-2">
        <p class="text-white bg-dark">copyright &copy; Shopall</p>
    </section>
</body>
</html>
		

templates/error.html
{% extends "base.html" %}
{% block start %}
<style>
    h1 {
        color: #ef1010;
        font-family: "Inter";
        font-weight: 900;
        font-size: 40px;
        margin-bottom: 10px;
    }

    p {
        color: #404F5E;
        font-family:"Inter";
        font-size: 20px;
        margin: 0;
    }

    i {
        color: #f24141;
        font-size: 100px;
        line-height: 200px;
        margin-left: 50px;
    }

    .c {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 4% auto;
    }
</style>
<div class="c">
    <div style="border-radius:200px; height:200px; width:200px; background: #e4c2c2; margin:0 auto;">
        <i class="checkmark">✘</i>
    </div>
    <h1>Server error</h1>
    <p>Please Try Again</p>
</div>
{% endblock %}

templates/invoice_mail.html
<div class="invoice-box">
    <table cellpadding="0" cellspacing="0">
        <tr class="top_rw">
            <td colspan="2">
                <h2 style="margin-bottom: 0px;"> Tax invoice/Bill of Supply/Cash memo </h2>
                <span> Number: 27B00032991LQ354 Date: 21-11-2018 </span>
            </td>
            <td style="width:30%; margin-right: 10px;">
                PaytmMall Order Id: {{payment_id}}
            </td>
        </tr>
        <tr class="top">
            <td colspan="3">
                <table>
                    <tr>
                        <td>
                            <b> Sold By: Nova Enterprises </b> <br>
                            Delhivery Pvt. Ltd. Plot No. A5 Indian Corporation <br>
                            Warehouse Park Village Dive-anjur, Bhiwandi, Off <br>
                            Nh-3, Near Mankoli Naka, District Thane, Pin Code :
                            421302 <br>
                            Mumbai, Maharashtra - 421302 <br>
                            PAN: AALFN0535C <br>
                            GSTIN: 27AALFN0535C1ZK <br>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr class="information">
            <td colspan="3">
                <table>
                    <tr>
                        <td colspan="2">
                            <b> Shipping Address: </b><br>
                            {{user.user.address.all.0.fist_line}}<br>
                            {{user.user.address.all.0.second_line}}<br>
                            {{user.user.address.all.0.city}},{{user.user.address.all.0.state}} <br>
                            {{user.user.address.all.0.phone_num}}
                            {{user.email}}<br>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <td colspan="3">
            <table cellspacing="0px" cellpadding="2px">
                <tr class="heading">
                    <td style="width:35%;">
                        ITEM
                    </td>
                    <td style="width:10%; text-align:center;">
                        QTY.
                    </td>
                    <td style="width:10%; text-align:right;">
                        PRICE (INR)
                    </td>
                    <td style="width:15%; text-align:right;">
                        TAX RATE & TYPE
                    </td>
                    <td style="width:15%; text-align:right;">
                        TAX AMOUNT (INR)
                    </td>
                    <td style="width:15%; text-align:right;">
                        TOTAL AMOUNT (INR)
                    </td>
                </tr>
                {% for item in order %}
                    <tr class="item">
                    
                        <td style="width:35%;">
                            <img src="{{ item.product.product_images.all.0.image.url }}" style="height:90px" />
                            {{ item.product.title }}
                            {{ item.product.preview_text }}
                        </td>
                        <td style="width:10%; text-align:center;">
                            1
                        </td>
                        <td style="width:10%; text-align:right;">
                            {{ item.product.price }}
                        </td>
                        <td style="width:15%; text-align:right;">
                            18% IGST
                        </td>
                        <td style="width:15%; text-align:right;">
                            {{ item.get_gst_price }}
                        </td>
                        <td style="width:15%; text-align:right;">
                            {{ item.get_product_price.0 }}
                        </td>
                    
                    </tr>
                {% endfor %}
                {% if coupon %}
                <tr class="item">
                    <td style="width:35%;"> <b> Coupon </b> </td>
                    <td style="width:10%; text-align:center;">
                    </td>
                    <td style="width:10%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                       -{{coupon.discount_price}}
                    </td>
                </tr>
                {% endif %}
                <tr class="item">
                    <td style="width:35%;"> <b> Grand Total </b> </td>
                    <td style="width:10%; text-align:center;">
                    </td>
                    <td style="width:10%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                    </td>
                    <td style="width:15%; text-align:right;">
                        {{total}}
                    </td>
                </tr>
                
        </td>
    </table>
    <tr class="total">
        <td colspan="3" align="right" style="border-top:solid 2px #333;"> Total Amount in Words : <b> {{ price_in_word }} Only </b> </td>
    </tr>
    <tr>
        <td colspan="3">
            <table cellspacing="0px" cellpadding="2px">
                <tr>
                    <td width="50%">
                        <b> Declaration: </b> <br>
                        We declare that this invoice shows the actual price of the goods
                        described above and that all particulars are true and correct. The
                        goods sold are intended for end user consumption and not for resale.
                    </td><br>
                    <td>
                        * This is a computer generated invoice and does not
                        require a physical signature
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</div>

<style>
    .top_rw {
        background-color: #f4f4f4;
    }

    button {
        padding: 5px 10px;
        font-size: 14px;
    }

    tr *{
        padding-top: 10px;
    }
    .invoice-box {
        max-width: 890px;
        margin: auto;
        padding: 10px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 14px;
        line-height: 24px;
        font-family: 'Inter';
        color: #555;
    }

    .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
        border-bottom: solid 1px #ccc;
    }

    .invoice-box table td {
        padding: 5px;
        vertical-align: middle;
    }

    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }

    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }

    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }

    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
        font-size: 12px;
    }

    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }

    .invoice-box table tr.item td {
        border-bottom: 1px solid #eee;
    }

    .invoice-box table tr.item.last td {
        border-bottom: none;
    }

    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }

    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }

        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }

    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: 'Inter';
    }

    .rtl table {
        text-align: right;
    }

    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
</style>

templates/success.html
{% extends "base.html" %}
{% block start %}
<style>
    h1 {
        color: #88B04B;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-weight: 900;
        font-size: 40px;
        margin-bottom: 10px;
    }

    p {
        color: #404F5E;
        font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
        font-size: 20px;
        margin: 0;
    }

    i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left: 50px;
    }

    .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 4% auto;
    }
</style>
<div class="card">
    <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
    </div>
    <h1>Success</h1>
    <p>We received your purchase request;<br /> Check Your email for payment confirmation!</p>
</div>
{% endblock %}